// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTWVmaUqvYQbOrDDSrD6yRXEujHXr0BO8',
    appId: '1:600306544641:web:a20d5705da688788235000',
    messagingSenderId: '600306544641',
    projectId: 'study-hub-75919',
    authDomain: 'study-hub-75919.firebaseapp.com',
    storageBucket: 'study-hub-75919.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn5aNqbFAgOv6CT8RkUS-Epemrc5H927k',
    appId: '1:600306544641:android:0abcc5407179f95f235000',
    messagingSenderId: '600306544641',
    projectId: 'study-hub-75919',
    storageBucket: 'study-hub-75919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3XDA7O_nnQu6GvkF9YYVEGv6c9MWL0_4',
    appId: '1:600306544641:ios:638c3680c1ae14de235000',
    messagingSenderId: '600306544641',
    projectId: 'study-hub-75919',
    storageBucket: 'study-hub-75919.firebasestorage.app',
    iosBundleId: 'com.example.studyHub',
  );
}
